INSERT INTO tani_provinces (id, code, name) VALUES (11, '11', 'ACEH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1101, 11, 'KABUPATEN SIMEULUE') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1102, 11, 'KABUPATEN ACEH SINGKIL') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1103, 11, 'KABUPATEN ACEH SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1104, 11, 'KABUPATEN ACEH TENGGARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1105, 11, 'KABUPATEN ACEH TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1106, 11, 'KABUPATEN ACEH TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1107, 11, 'KABUPATEN ACEH BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1108, 11, 'KABUPATEN ACEH BESAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1109, 11, 'KABUPATEN PIDIE') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1110, 11, 'KABUPATEN BIREUEN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1111, 11, 'KABUPATEN ACEH UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1112, 11, 'KABUPATEN ACEH BARAT DAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1113, 11, 'KABUPATEN GAYO LUES') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1114, 11, 'KABUPATEN ACEH TAMIANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1115, 11, 'KABUPATEN NAGAN RAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1116, 11, 'KABUPATEN ACEH JAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1117, 11, 'KABUPATEN BENER MERIAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1118, 11, 'KABUPATEN PIDIE JAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1171, 11, 'KOTA BANDA ACEH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1172, 11, 'KOTA SABANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1173, 11, 'KOTA LANGSA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1174, 11, 'KOTA LHOKSEUMAWE') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1175, 11, 'KOTA SUBULUSSALAM') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (12, '12', 'SUMATERA UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1201, 12, 'KABUPATEN NIAS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1202, 12, 'KABUPATEN MANDAILING NATAL') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1203, 12, 'KABUPATEN TAPANULI SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1204, 12, 'KABUPATEN TAPANULI TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1205, 12, 'KABUPATEN TAPANULI UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1206, 12, 'KABUPATEN TOBA SAMOSIR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1207, 12, 'KABUPATEN LABUHAN BATU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1208, 12, 'KABUPATEN ASAHAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1209, 12, 'KABUPATEN SIMALUNGUN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1210, 12, 'KABUPATEN DAIRI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1211, 12, 'KABUPATEN KARO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1212, 12, 'KABUPATEN DELI SERDANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1213, 12, 'KABUPATEN LANGKAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1214, 12, 'KABUPATEN NIAS SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1215, 12, 'KABUPATEN HUMBANG HASUNDUTAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1216, 12, 'KABUPATEN PAKPAK BHARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1217, 12, 'KABUPATEN SAMOSIR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1218, 12, 'KABUPATEN SERDANG BEDAGAI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1219, 12, 'KABUPATEN BATU BARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1220, 12, 'KABUPATEN PADANG LAWAS UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1221, 12, 'KABUPATEN PADANG LAWAS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1222, 12, 'KABUPATEN LABUHAN BATU SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1223, 12, 'KABUPATEN LABUHAN BATU UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1224, 12, 'KABUPATEN NIAS UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1225, 12, 'KABUPATEN NIAS BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1271, 12, 'KOTA SIBOLGA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1272, 12, 'KOTA TANJUNG BALAI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1273, 12, 'KOTA PEMATANG SIANTAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1274, 12, 'KOTA TEBING TINGGI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1275, 12, 'KOTA MEDAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1276, 12, 'KOTA BINJAI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1277, 12, 'KOTA PADANGSIDIMPUAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1278, 12, 'KOTA GUNUNGSITOLI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (13, '13', 'SUMATERA BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1301, 13, 'KABUPATEN KEPULAUAN MENTAWAI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1302, 13, 'KABUPATEN PESISIR SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1303, 13, 'KABUPATEN SOLOK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1304, 13, 'KABUPATEN SIJUNJUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1305, 13, 'KABUPATEN TANAH DATAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1306, 13, 'KABUPATEN PADANG PARIAMAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1307, 13, 'KABUPATEN AGAM') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1308, 13, 'KABUPATEN LIMA PULUH KOTA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1309, 13, 'KABUPATEN PASAMAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1310, 13, 'KABUPATEN SOLOK SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1311, 13, 'KABUPATEN DHARMASRAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1312, 13, 'KABUPATEN PASAMAN BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1371, 13, 'KOTA PADANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1372, 13, 'KOTA SOLOK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1373, 13, 'KOTA SAWAH LUNTO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1374, 13, 'KOTA PADANG PANJANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1375, 13, 'KOTA BUKITTINGGI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1376, 13, 'KOTA PAYAKUMBUH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1377, 13, 'KOTA PARIAMAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (14, '14', 'RIAU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1401, 14, 'KABUPATEN KUANTAN SINGINGI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1402, 14, 'KABUPATEN INDRAGIRI HULU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1403, 14, 'KABUPATEN INDRAGIRI HILIR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1404, 14, 'KABUPATEN PELALAWAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1405, 14, 'KABUPATEN S I A K') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1406, 14, 'KABUPATEN KAMPAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1407, 14, 'KABUPATEN ROKAN HULU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1408, 14, 'KABUPATEN BENGKALIS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1409, 14, 'KABUPATEN ROKAN HILIR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1410, 14, 'KABUPATEN KEPULAUAN MERANTI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1471, 14, 'KOTA PEKANBARU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1473, 14, 'KOTA D U M A I') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (15, '15', 'JAMBI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1501, 15, 'KABUPATEN KERINCI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1502, 15, 'KABUPATEN MERANGIN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1503, 15, 'KABUPATEN SAROLANGUN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1504, 15, 'KABUPATEN BATANG HARI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1505, 15, 'KABUPATEN MUARO JAMBI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1506, 15, 'KABUPATEN TANJUNG JABUNG TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1507, 15, 'KABUPATEN TANJUNG JABUNG BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1508, 15, 'KABUPATEN TEBO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1509, 15, 'KABUPATEN BUNGO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1571, 15, 'KOTA JAMBI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1572, 15, 'KOTA SUNGAI PENUH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (16, '16', 'SUMATERA SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1601, 16, 'KABUPATEN OGAN KOMERING ULU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1602, 16, 'KABUPATEN OGAN KOMERING ILIR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1603, 16, 'KABUPATEN MUARA ENIM') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1604, 16, 'KABUPATEN LAHAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1605, 16, 'KABUPATEN MUSI RAWAS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1606, 16, 'KABUPATEN MUSI BANYUASIN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1607, 16, 'KABUPATEN BANYU ASIN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1608, 16, 'KABUPATEN OGAN KOMERING ULU SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1609, 16, 'KABUPATEN OGAN KOMERING ULU TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1610, 16, 'KABUPATEN OGAN ILIR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1611, 16, 'KABUPATEN EMPAT LAWANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1612, 16, 'KABUPATEN PENUKAL ABAB LEMATANG ILIR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1613, 16, 'KABUPATEN MUSI RAWAS UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1671, 16, 'KOTA PALEMBANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1672, 16, 'KOTA PRABUMULIH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1673, 16, 'KOTA PAGAR ALAM') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1674, 16, 'KOTA LUBUKLINGGAU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (17, '17', 'BENGKULU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1701, 17, 'KABUPATEN BENGKULU SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1702, 17, 'KABUPATEN REJANG LEBONG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1703, 17, 'KABUPATEN BENGKULU UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1704, 17, 'KABUPATEN KAUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1705, 17, 'KABUPATEN SELUMA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1706, 17, 'KABUPATEN MUKOMUKO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1707, 17, 'KABUPATEN LEBONG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1708, 17, 'KABUPATEN KEPAHIANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1709, 17, 'KABUPATEN BENGKULU TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1771, 17, 'KOTA BENGKULU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (18, '18', 'LAMPUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1801, 18, 'KABUPATEN LAMPUNG BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1802, 18, 'KABUPATEN TANGGAMUS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1803, 18, 'KABUPATEN LAMPUNG SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1804, 18, 'KABUPATEN LAMPUNG TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1805, 18, 'KABUPATEN LAMPUNG TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1806, 18, 'KABUPATEN LAMPUNG UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1807, 18, 'KABUPATEN WAY KANAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1808, 18, 'KABUPATEN TULANGBAWANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1809, 18, 'KABUPATEN PESAWARAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1810, 18, 'KABUPATEN PRINGSEWU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1811, 18, 'KABUPATEN MESUJI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1812, 18, 'KABUPATEN TULANG BAWANG BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1813, 18, 'KABUPATEN PESISIR BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1871, 18, 'KOTA BANDAR LAMPUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1872, 18, 'KOTA METRO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (19, '19', 'KEPULAUAN BANGKA BELITUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1901, 19, 'KABUPATEN BANGKA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1902, 19, 'KABUPATEN BELITUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1903, 19, 'KABUPATEN BANGKA BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1904, 19, 'KABUPATEN BANGKA TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1905, 19, 'KABUPATEN BANGKA SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1906, 19, 'KABUPATEN BELITUNG TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (1971, 19, 'KOTA PANGKAL PINANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (21, '21', 'KEPULAUAN RIAU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (2101, 21, 'KABUPATEN KARIMUN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (2102, 21, 'KABUPATEN BINTAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (2103, 21, 'KABUPATEN NATUNA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (2104, 21, 'KABUPATEN LINGGA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (2105, 21, 'KABUPATEN KEPULAUAN ANAMBAS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (2171, 21, 'KOTA B A T A M') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (2172, 21, 'KOTA TANJUNG PINANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (31, '31', 'DKI JAKARTA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3101, 31, 'KABUPATEN KEPULAUAN SERIBU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3171, 31, 'KOTA JAKARTA SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3172, 31, 'KOTA JAKARTA TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3173, 31, 'KOTA JAKARTA PUSAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3174, 31, 'KOTA JAKARTA BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3175, 31, 'KOTA JAKARTA UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (32, '32', 'JAWA BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3201, 32, 'KABUPATEN BOGOR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3202, 32, 'KABUPATEN SUKABUMI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3203, 32, 'KABUPATEN CIANJUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3204, 32, 'KABUPATEN BANDUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3205, 32, 'KABUPATEN GARUT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3206, 32, 'KABUPATEN TASIKMALAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3207, 32, 'KABUPATEN CIAMIS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3208, 32, 'KABUPATEN KUNINGAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3209, 32, 'KABUPATEN CIREBON') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3210, 32, 'KABUPATEN MAJALENGKA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3211, 32, 'KABUPATEN SUMEDANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3212, 32, 'KABUPATEN INDRAMAYU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3213, 32, 'KABUPATEN SUBANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3214, 32, 'KABUPATEN PURWAKARTA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3215, 32, 'KABUPATEN KARAWANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3216, 32, 'KABUPATEN BEKASI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3217, 32, 'KABUPATEN BANDUNG BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3218, 32, 'KABUPATEN PANGANDARAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3271, 32, 'KOTA BOGOR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3272, 32, 'KOTA SUKABUMI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3273, 32, 'KOTA BANDUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3274, 32, 'KOTA CIREBON') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3275, 32, 'KOTA BEKASI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3276, 32, 'KOTA DEPOK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3277, 32, 'KOTA CIMAHI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3278, 32, 'KOTA TASIKMALAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3279, 32, 'KOTA BANJAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (33, '33', 'JAWA TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3301, 33, 'KABUPATEN CILACAP') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3302, 33, 'KABUPATEN BANYUMAS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3303, 33, 'KABUPATEN PURBALINGGA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3304, 33, 'KABUPATEN BANJARNEGARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3305, 33, 'KABUPATEN KEBUMEN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3306, 33, 'KABUPATEN PURWOREJO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3307, 33, 'KABUPATEN WONOSOBO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3308, 33, 'KABUPATEN MAGELANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3309, 33, 'KABUPATEN BOYOLALI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3310, 33, 'KABUPATEN KLATEN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3311, 33, 'KABUPATEN SUKOHARJO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3312, 33, 'KABUPATEN WONOGIRI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3313, 33, 'KABUPATEN KARANGANYAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3314, 33, 'KABUPATEN SRAGEN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3315, 33, 'KABUPATEN GROBOGAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3316, 33, 'KABUPATEN BLORA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3317, 33, 'KABUPATEN REMBANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3318, 33, 'KABUPATEN PATI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3319, 33, 'KABUPATEN KUDUS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3320, 33, 'KABUPATEN JEPARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3321, 33, 'KABUPATEN DEMAK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3322, 33, 'KABUPATEN SEMARANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3323, 33, 'KABUPATEN TEMANGGUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3324, 33, 'KABUPATEN KENDAL') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3325, 33, 'KABUPATEN BATANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3326, 33, 'KABUPATEN PEKALONGAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3327, 33, 'KABUPATEN PEMALANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3328, 33, 'KABUPATEN TEGAL') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3329, 33, 'KABUPATEN BREBES') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3371, 33, 'KOTA MAGELANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3372, 33, 'KOTA SURAKARTA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3373, 33, 'KOTA SALATIGA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3374, 33, 'KOTA SEMARANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3375, 33, 'KOTA PEKALONGAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3376, 33, 'KOTA TEGAL') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (34, '34', 'DI YOGYAKARTA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3401, 34, 'KABUPATEN KULON PROGO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3402, 34, 'KABUPATEN BANTUL') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3403, 34, 'KABUPATEN GUNUNG KIDUL') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3404, 34, 'KABUPATEN SLEMAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3471, 34, 'KOTA YOGYAKARTA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (35, '35', 'JAWA TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3501, 35, 'KABUPATEN PACITAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3502, 35, 'KABUPATEN PONOROGO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3503, 35, 'KABUPATEN TRENGGALEK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3504, 35, 'KABUPATEN TULUNGAGUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3505, 35, 'KABUPATEN BLITAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3506, 35, 'KABUPATEN KEDIRI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3507, 35, 'KABUPATEN MALANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3508, 35, 'KABUPATEN LUMAJANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3509, 35, 'KABUPATEN JEMBER') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3510, 35, 'KABUPATEN BANYUWANGI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3511, 35, 'KABUPATEN BONDOWOSO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3512, 35, 'KABUPATEN SITUBONDO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3513, 35, 'KABUPATEN PROBOLINGGO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3514, 35, 'KABUPATEN PASURUAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3515, 35, 'KABUPATEN SIDOARJO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3516, 35, 'KABUPATEN MOJOKERTO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3517, 35, 'KABUPATEN JOMBANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3518, 35, 'KABUPATEN NGANJUK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3519, 35, 'KABUPATEN MADIUN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3520, 35, 'KABUPATEN MAGETAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3521, 35, 'KABUPATEN NGAWI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3522, 35, 'KABUPATEN BOJONEGORO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3523, 35, 'KABUPATEN TUBAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3524, 35, 'KABUPATEN LAMONGAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3525, 35, 'KABUPATEN GRESIK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3526, 35, 'KABUPATEN BANGKALAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3527, 35, 'KABUPATEN SAMPANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3528, 35, 'KABUPATEN PAMEKASAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3529, 35, 'KABUPATEN SUMENEP') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3571, 35, 'KOTA KEDIRI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3572, 35, 'KOTA BLITAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3573, 35, 'KOTA MALANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3574, 35, 'KOTA PROBOLINGGO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3575, 35, 'KOTA PASURUAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3576, 35, 'KOTA MOJOKERTO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3577, 35, 'KOTA MADIUN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3578, 35, 'KOTA SURABAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3579, 35, 'KOTA BATU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (36, '36', 'BANTEN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3601, 36, 'KABUPATEN PANDEGLANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3602, 36, 'KABUPATEN LEBAK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3603, 36, 'KABUPATEN TANGERANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3604, 36, 'KABUPATEN SERANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3671, 36, 'KOTA TANGERANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3672, 36, 'KOTA CILEGON') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3673, 36, 'KOTA SERANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (3674, 36, 'KOTA TANGERANG SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (51, '51', 'BALI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5101, 51, 'KABUPATEN JEMBRANA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5102, 51, 'KABUPATEN TABANAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5103, 51, 'KABUPATEN BADUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5104, 51, 'KABUPATEN GIANYAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5105, 51, 'KABUPATEN KLUNGKUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5106, 51, 'KABUPATEN BANGLI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5107, 51, 'KABUPATEN KARANG ASEM') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5108, 51, 'KABUPATEN BULELENG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5171, 51, 'KOTA DENPASAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (52, '52', 'NUSA TENGGARA BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5201, 52, 'KABUPATEN LOMBOK BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5202, 52, 'KABUPATEN LOMBOK TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5203, 52, 'KABUPATEN LOMBOK TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5204, 52, 'KABUPATEN SUMBAWA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5205, 52, 'KABUPATEN DOMPU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5206, 52, 'KABUPATEN BIMA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5207, 52, 'KABUPATEN SUMBAWA BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5208, 52, 'KABUPATEN LOMBOK UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5271, 52, 'KOTA MATARAM') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5272, 52, 'KOTA BIMA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (53, '53', 'NUSA TENGGARA TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5301, 53, 'KABUPATEN SUMBA BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5302, 53, 'KABUPATEN SUMBA TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5303, 53, 'KABUPATEN KUPANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5304, 53, 'KABUPATEN TIMOR TENGAH SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5305, 53, 'KABUPATEN TIMOR TENGAH UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5306, 53, 'KABUPATEN BELU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5307, 53, 'KABUPATEN ALOR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5308, 53, 'KABUPATEN LEMBATA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5309, 53, 'KABUPATEN FLORES TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5310, 53, 'KABUPATEN SIKKA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5311, 53, 'KABUPATEN ENDE') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5312, 53, 'KABUPATEN NGADA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5313, 53, 'KABUPATEN MANGGARAI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5314, 53, 'KABUPATEN ROTE NDAO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5315, 53, 'KABUPATEN MANGGARAI BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5316, 53, 'KABUPATEN SUMBA TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5317, 53, 'KABUPATEN SUMBA BARAT DAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5318, 53, 'KABUPATEN NAGEKEO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5319, 53, 'KABUPATEN MANGGARAI TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5320, 53, 'KABUPATEN SABU RAIJUA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5321, 53, 'KABUPATEN MALAKA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (5371, 53, 'KOTA KUPANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (61, '61', 'KALIMANTAN BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6101, 61, 'KABUPATEN SAMBAS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6102, 61, 'KABUPATEN BENGKAYANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6103, 61, 'KABUPATEN LANDAK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6104, 61, 'KABUPATEN MEMPAWAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6105, 61, 'KABUPATEN SANGGAU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6106, 61, 'KABUPATEN KETAPANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6107, 61, 'KABUPATEN SINTANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6108, 61, 'KABUPATEN KAPUAS HULU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6109, 61, 'KABUPATEN SEKADAU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6110, 61, 'KABUPATEN MELAWI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6111, 61, 'KABUPATEN KAYONG UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6112, 61, 'KABUPATEN KUBU RAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6171, 61, 'KOTA PONTIANAK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6172, 61, 'KOTA SINGKAWANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (62, '62', 'KALIMANTAN TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6201, 62, 'KABUPATEN KOTAWARINGIN BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6202, 62, 'KABUPATEN KOTAWARINGIN TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6203, 62, 'KABUPATEN KAPUAS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6204, 62, 'KABUPATEN BARITO SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6205, 62, 'KABUPATEN BARITO UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6206, 62, 'KABUPATEN SUKAMARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6207, 62, 'KABUPATEN LAMANDAU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6208, 62, 'KABUPATEN SERUYAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6209, 62, 'KABUPATEN KATINGAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6210, 62, 'KABUPATEN PULANG PISAU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6211, 62, 'KABUPATEN GUNUNG MAS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6212, 62, 'KABUPATEN BARITO TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6213, 62, 'KABUPATEN MURUNG RAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6271, 62, 'KOTA PALANGKA RAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (63, '63', 'KALIMANTAN SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6301, 63, 'KABUPATEN TANAH LAUT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6302, 63, 'KABUPATEN KOTA BARU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6303, 63, 'KABUPATEN BANJAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6304, 63, 'KABUPATEN BARITO KUALA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6305, 63, 'KABUPATEN TAPIN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6306, 63, 'KABUPATEN HULU SUNGAI SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6307, 63, 'KABUPATEN HULU SUNGAI TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6308, 63, 'KABUPATEN HULU SUNGAI UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6309, 63, 'KABUPATEN TABALONG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6310, 63, 'KABUPATEN TANAH BUMBU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6311, 63, 'KABUPATEN BALANGAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6371, 63, 'KOTA BANJARMASIN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6372, 63, 'KOTA BANJAR BARU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (64, '64', 'KALIMANTAN TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6401, 64, 'KABUPATEN PASER') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6402, 64, 'KABUPATEN KUTAI BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6403, 64, 'KABUPATEN KUTAI KARTANEGARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6404, 64, 'KABUPATEN KUTAI TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6405, 64, 'KABUPATEN BERAU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6409, 64, 'KABUPATEN PENAJAM PASER UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6411, 64, 'KABUPATEN MAHAKAM HULU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6471, 64, 'KOTA BALIKPAPAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6472, 64, 'KOTA SAMARINDA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6474, 64, 'KOTA BONTANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (65, '65', 'KALIMANTAN UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6501, 65, 'KABUPATEN MALINAU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6502, 65, 'KABUPATEN BULUNGAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6503, 65, 'KABUPATEN TANA TIDUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6504, 65, 'KABUPATEN NUNUKAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (6571, 65, 'KOTA TARAKAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (71, '71', 'SULAWESI UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7101, 71, 'KABUPATEN BOLAANG MONGONDOW') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7102, 71, 'KABUPATEN MINAHASA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7103, 71, 'KABUPATEN KEPULAUAN SANGIHE') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7104, 71, 'KABUPATEN KEPULAUAN TALAUD') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7105, 71, 'KABUPATEN MINAHASA SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7106, 71, 'KABUPATEN MINAHASA UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7107, 71, 'KABUPATEN BOLAANG MONGONDOW UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7108, 71, 'KABUPATEN SIAU TAGULANDANG BIARO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7109, 71, 'KABUPATEN MINAHASA TENGGARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7110, 71, 'KABUPATEN BOLAANG MONGONDOW SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7111, 71, 'KABUPATEN BOLAANG MONGONDOW TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7171, 71, 'KOTA MANADO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7172, 71, 'KOTA BITUNG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7173, 71, 'KOTA TOMOHON') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7174, 71, 'KOTA KOTAMOBAGU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (72, '72', 'SULAWESI TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7201, 72, 'KABUPATEN BANGGAI KEPULAUAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7202, 72, 'KABUPATEN BANGGAI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7203, 72, 'KABUPATEN MOROWALI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7204, 72, 'KABUPATEN POSO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7205, 72, 'KABUPATEN DONGGALA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7206, 72, 'KABUPATEN TOLI-TOLI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7207, 72, 'KABUPATEN BUOL') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7208, 72, 'KABUPATEN PARIGI MOUTONG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7209, 72, 'KABUPATEN TOJO UNA-UNA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7210, 72, 'KABUPATEN SIGI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7211, 72, 'KABUPATEN BANGGAI LAUT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7212, 72, 'KABUPATEN MOROWALI UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7271, 72, 'KOTA PALU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (73, '73', 'SULAWESI SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7301, 73, 'KABUPATEN KEPULAUAN SELAYAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7302, 73, 'KABUPATEN BULUKUMBA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7303, 73, 'KABUPATEN BANTAENG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7304, 73, 'KABUPATEN JENEPONTO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7305, 73, 'KABUPATEN TAKALAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7306, 73, 'KABUPATEN GOWA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7307, 73, 'KABUPATEN SINJAI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7308, 73, 'KABUPATEN MAROS') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7309, 73, 'KABUPATEN PANGKAJENE DAN KEPULAUAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7310, 73, 'KABUPATEN BARRU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7311, 73, 'KABUPATEN BONE') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7312, 73, 'KABUPATEN SOPPENG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7313, 73, 'KABUPATEN WAJO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7314, 73, 'KABUPATEN SIDENRENG RAPPANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7315, 73, 'KABUPATEN PINRANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7316, 73, 'KABUPATEN ENREKANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7317, 73, 'KABUPATEN LUWU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7318, 73, 'KABUPATEN TANA TORAJA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7322, 73, 'KABUPATEN LUWU UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7325, 73, 'KABUPATEN LUWU TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7326, 73, 'KABUPATEN TORAJA UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7371, 73, 'KOTA MAKASSAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7372, 73, 'KOTA PAREPARE') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7373, 73, 'KOTA PALOPO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (74, '74', 'SULAWESI TENGGARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7401, 74, 'KABUPATEN BUTON') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7402, 74, 'KABUPATEN MUNA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7403, 74, 'KABUPATEN KONAWE') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7404, 74, 'KABUPATEN KOLAKA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7405, 74, 'KABUPATEN KONAWE SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7406, 74, 'KABUPATEN BOMBANA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7407, 74, 'KABUPATEN WAKATOBI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7408, 74, 'KABUPATEN KOLAKA UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7409, 74, 'KABUPATEN BUTON UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7410, 74, 'KABUPATEN KONAWE UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7411, 74, 'KABUPATEN KOLAKA TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7412, 74, 'KABUPATEN KONAWE KEPULAUAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7413, 74, 'KABUPATEN MUNA BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7414, 74, 'KABUPATEN BUTON TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7415, 74, 'KABUPATEN BUTON SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7471, 74, 'KOTA KENDARI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7472, 74, 'KOTA BAUBAU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (75, '75', 'GORONTALO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7501, 75, 'KABUPATEN BOALEMO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7502, 75, 'KABUPATEN GORONTALO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7503, 75, 'KABUPATEN POHUWATO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7504, 75, 'KABUPATEN BONE BOLANGO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7505, 75, 'KABUPATEN GORONTALO UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7571, 75, 'KOTA GORONTALO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (76, '76', 'SULAWESI BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7601, 76, 'KABUPATEN MAJENE') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7602, 76, 'KABUPATEN POLEWALI MANDAR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7603, 76, 'KABUPATEN MAMASA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7604, 76, 'KABUPATEN MAMUJU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7605, 76, 'KABUPATEN MAMUJU UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (7606, 76, 'KABUPATEN MAMUJU TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (81, '81', 'MALUKU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8101, 81, 'KABUPATEN MALUKU TENGGARA BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8102, 81, 'KABUPATEN MALUKU TENGGARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8103, 81, 'KABUPATEN MALUKU TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8104, 81, 'KABUPATEN BURU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8105, 81, 'KABUPATEN KEPULAUAN ARU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8106, 81, 'KABUPATEN SERAM BAGIAN BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8107, 81, 'KABUPATEN SERAM BAGIAN TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8108, 81, 'KABUPATEN MALUKU BARAT DAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8109, 81, 'KABUPATEN BURU SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8171, 81, 'KOTA AMBON') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8172, 81, 'KOTA TUAL') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (82, '82', 'MALUKU UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8201, 82, 'KABUPATEN HALMAHERA BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8202, 82, 'KABUPATEN HALMAHERA TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8203, 82, 'KABUPATEN KEPULAUAN SULA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8204, 82, 'KABUPATEN HALMAHERA SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8205, 82, 'KABUPATEN HALMAHERA UTARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8206, 82, 'KABUPATEN HALMAHERA TIMUR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8207, 82, 'KABUPATEN PULAU MOROTAI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8208, 82, 'KABUPATEN PULAU TALIABU') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8271, 82, 'KOTA TERNATE') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (8272, 82, 'KOTA TIDORE KEPULAUAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (91, '91', 'PAPUA BARAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9101, 91, 'KABUPATEN FAKFAK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9102, 91, 'KABUPATEN KAIMANA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9103, 91, 'KABUPATEN TELUK WONDAMA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9104, 91, 'KABUPATEN TELUK BINTUNI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9105, 91, 'KABUPATEN MANOKWARI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9106, 91, 'KABUPATEN SORONG SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9107, 91, 'KABUPATEN SORONG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9108, 91, 'KABUPATEN RAJA AMPAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9109, 91, 'KABUPATEN TAMBRAUW') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9110, 91, 'KABUPATEN MAYBRAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9111, 91, 'KABUPATEN MANOKWARI SELATAN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9112, 91, 'KABUPATEN PEGUNUNGAN ARFAK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9171, 91, 'KOTA SORONG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_provinces (id, code, name) VALUES (94, '94', 'PAPUA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9401, 94, 'KABUPATEN MERAUKE') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9402, 94, 'KABUPATEN JAYAWIJAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9403, 94, 'KABUPATEN JAYAPURA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9404, 94, 'KABUPATEN NABIRE') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9408, 94, 'KABUPATEN KEPULAUAN YAPEN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9409, 94, 'KABUPATEN BIAK NUMFOR') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9410, 94, 'KABUPATEN PANIAI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9411, 94, 'KABUPATEN PUNCAK JAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9412, 94, 'KABUPATEN MIMIKA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9413, 94, 'KABUPATEN BOVEN DIGOEL') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9414, 94, 'KABUPATEN MAPPI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9415, 94, 'KABUPATEN ASMAT') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9416, 94, 'KABUPATEN YAHUKIMO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9417, 94, 'KABUPATEN PEGUNUNGAN BINTANG') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9418, 94, 'KABUPATEN TOLIKARA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9419, 94, 'KABUPATEN SARMI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9420, 94, 'KABUPATEN KEEROM') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9426, 94, 'KABUPATEN WAROPEN') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9427, 94, 'KABUPATEN SUPIORI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9428, 94, 'KABUPATEN MAMBERAMO RAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9429, 94, 'KABUPATEN NDUGA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9430, 94, 'KABUPATEN LANNY JAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9431, 94, 'KABUPATEN MAMBERAMO TENGAH') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9432, 94, 'KABUPATEN YALIMO') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9433, 94, 'KABUPATEN PUNCAK') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9434, 94, 'KABUPATEN DOGIYAI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9435, 94, 'KABUPATEN INTAN JAYA') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9436, 94, 'KABUPATEN DEIYAI') ON CONFLICT (id) DO NOTHING;
INSERT INTO tani_cities (id, province_id, name) VALUES (9471, 94, 'KOTA JAYAPURA') ON CONFLICT (id) DO NOTHING;
